In [6]:
## (c) Veronica Helms
## Team Neighborhood
## Last updated: 7/29/2016

######################

## import dependencies
import urllib2
import os
import openpyxl
import pandas as pd
import csv

In [45]:
# Creates directory for data - CBSA - FIPS CROSSWALK
CBSA = os.path.join(os.getcwd(),"CBSA") #folder name - if this doesnt exist then make it
if not os.path.exists(CBSA):
    os.makedirs(CBSA)

filename = CBSA + "/" + "FIPS_CBSA.csv"
url= "http://www.nber.org/cbsa-csa-fips-county-crosswalk/cbsa2fipsxw.csv"

f = urllib2.urlopen(url)
data = f.read()
with open(filename, "wb") as code:
    code.write(data)

In [53]:
df = pd.read_csv('FIPS_CBSA.csv', converters={'fipsstatecode': lambda x: str(x) ,
                                              'fipscountycode': lambda x: str(x) } )

In [54]:
df [['fipsstatecode', "cbsacode", 'fipscountycode']] #view obs

     fipsstatecode  cbsacode fipscountycode
0                        NaN
1               01     33860            001
2               01     19300            003
3               01     13820            007
4               01     13820            009
5               01     11500            015
6               01     46740            017
7               01     13820            021
8               01     21460            031
9               01     22520            033
10              01     45180            037
11              01     18980            043
12              01     37120            045
13              01     42820            047
14              01     33860            051
15              01     23460            055
16              01     20020            061
17              01     46220            065
18              01     20020            067
19              01     20020            069
20              01     42460            071
21              01     13820            073
22              01     22520            077
23              01     19460            079
24              01     12220            081
25              01     26620            083
26              01     33860            085
27              01     26620            089
28              01     10700            095
29              01     33660            097
...            ...       ...            ...
1853            72     41980            091
1854            72     41980            095
1855            72     32420            097
1856            72     10380            099
1857            72     41980            101
1858            72     41980            103
1859            72     41980            105
1860            72     41980            107
1861            72     25020            109
1862            72     38660            111
1863            72     38660            113
1864            72     11640            115
1865            72     10380            117
1866            72     41980            119
1867            72     41900            121
1868            72     17640            123
1869            72     41900            125
1870            72     41980            127
1871            72     41980            129
1872            72     10380            131
1873            72     42180            133
1874            72     41980            135
1875            72     41980            137
1876            72     41980            139
1877            72     10380            141
1878            72     41980            143
1879            72     41980            145
1880            72     38660            149
1881            72     41980            151
1882            72     38660            153

[1883 rows x 3 columns]

In [56]:
df["FIPS"] = df["fipsstatecode"].map(str) + df["fipscountycode"]

In [57]:
df [["cbsacode", 'FIPS']] #view obs

      cbsacode   FIPS
0          NaN
1        33860  01001
2        19300  01003
3        13820  01007
4        13820  01009
5        11500  01015
6        46740  01017
7        13820  01021
8        21460  01031
9        22520  01033
10       45180  01037
11       18980  01043
12       37120  01045
13       42820  01047
14       33860  01051
15       23460  01055
16       20020  01061
17       46220  01065
18       20020  01067
19       20020  01069
20       42460  01071
21       13820  01073
22       22520  01077
23       19460  01079
24       12220  01081
25       26620  01083
26       33860  01085
27       26620  01089
28       10700  01095
29       33660  01097
...        ...    ...
1853     41980  72091
1854     41980  72095
1855     32420  72097
1856     10380  72099
1857     41980  72101
1858     41980  72103
1859     41980  72105
1860     41980  72107
1861     25020  72109
1862     38660  72111
1863     38660  72113
1864     11640  72115
1865     10380  72117
1866     41980  72119
1867     41900  72121
1868     17640  72123
1869     41900  72125
1870     41980  72127
1871     41980  72129
1872     10380  72131
1873     42180  72133
1874     41980  72135
1875     41980  72137
1876     41980  72139
1877     10380  72141
1878     41980  72143
1879     41980  72145
1880     38660  72149
1881     41980  72151
1882     38660  72153

[1883 rows x 2 columns]

In [58]:
CBSA = df[['FIPS','cbsacode']]

       FIPS  cbsacode
0                 NaN
1     01001     33860
2     01003     19300
3     01007     13820
4     01009     13820
5     01015     11500
6     01017     46740
7     01021     13820
8     01031     21460
9     01033     22520
10    01037     45180
11    01043     18980
12    01045     37120
13    01047     42820
14    01051     33860
15    01055     23460
16    01061     20020
17    01065     46220
18    01067     20020
19    01069     20020
20    01071     42460
21    01073     13820
22    01077     22520
23    01079     19460
24    01081     12220
25    01083     26620
26    01085     33860
27    01089     26620
28    01095     10700
29    01097     33660
...     ...       ...
1853  72091     41980
1854  72095     41980
1855  72097     32420
1856  72099     10380
1857  72101     41980
1858  72103     41980
1859  72105     41980
1860  72107     41980
1861  72109     25020
1862  72111     38660
1863  72113     38660
1864  72115     11640
1865  72117     10380
1866  72119     41980
1867  72121     41900
1868  72123     17640
1869  72125     41900
1870  72127     41980
1871  72129     41980
1872  72131     10380
1873  72133     42180
1874  72135     41980
1875  72137     41980
1876  72139     41980
1877  72141     10380
1878  72143     41980
1879  72145     41980
1880  72149     38660
1881  72151     41980
1882  72153     38660

[1883 rows x 2 columns]